const GET_SKILL_REQUEST = 'GET_SKILLS_REQUEST'
const GET_SKILL_SUCCES = 'GET_SKILLS_SUCCESS'
const GET_SKILL_ERROR = 'GET_SKILLS_ERROR'
const GET_SKILL_BY_SLUG_ERROR = 'GET_SKILL_BY_SLUG_ERROR'
const GET_SKILL_BY_SLUG_REQUEST = 'GET_SKILL_BY_SLUG_REQUEST'
const GET_SKILL_BY_SLUG_SUCCES = 'GET_SKILL_BY_SLUG_SUCCESS'
export {
    GET_SKILL_ERROR,
    GET_SKILL_REQUEST,
    GET_SKILL_SUCCES,
    GET_SKILL_BY_SLUG_ERROR,
    GET_SKILL_BY_SLUG_REQUEST,
    GET_SKILL_BY_SLUG_SUCCES
}